# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e623f01004f0bc22d8f1c9321e804bfa09b908f1e90707e1ce3163cc76bc5dae924e8f1a2b400d0f7ef4600b54537e8982e89974213681c877d4a8872b88bb6

test:
  secret_key_base: 75872bb17464136cc2ff7e1258d533f5ba8713c7060e94e6a09b3d5c4363b36e750f0aae2e5c69183cdd4fec94d5dcd1c6d8e346d6445a420b9a8c2d9eb29a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
